name: IBM App Connect Enterprise 
description: |
  IBM® App Connect Enterprise software combines the existing, industry-trusted technologies of IBM Integration Bus with IBM App Connect Professional and with cloud native technologies, to deliver a platform that supports the full breadth of integration needs across a modern digital enterprise.
version: 12.0.05
category: "IBM Software"